name: Mise à jour mensuelle des données GTFS

on:
  schedule:
    - cron: '30 6 1 * *'
  
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Déclencher le déploiement sur Render
        run: curl -X POST "https://api.render.com/deploy/srv-d0peuuemcj7s73e2fm3g?key=mEClXbQZln4"